const START = "START"
const RESTART = "RESTART"
const PLAYER_HIT = "PLAYER_HIT"
const PLAYER_STAY = "PLAYER_STAY"
const DEALER_HIT = "DEALER_HIT"
const DEALER_STAY = "DEALER_STAY"
const CALCULATE = "CALCULATE"

export { 
   START, 
   RESTART, 
   PLAYER_HIT, 
   PLAYER_STAY, 
   DEALER_HIT, 
   DEALER_STAY, 
   CALCULATE 
}